### ISSUE TITLE
Basic Example in the Readme incorrect?

### ISSUE THREAD

**Issue by axelson** [sheerun/dataloader#3]
Here is the basic example:

```
# It will be called only once with ids = [1, 2, 3]
loader = Dataloader.new do |ids|
  User.find(*ids)
end

# Schedule data to load
promise_one = loader.load(0)
promise_two = loader.load_many([1, 2])

# Get promises results
user0 = promise_one.sync
user1, user2 = promise_two.sync
```

Shouldn't `promise_one = loader.load(0)` be `promise_one = loader.load(3)` instead?

Or `# It will be called only once with ids = [1, 2, 3]` should be `# It will be called only once with ids = [0, 1, 2]`

**Comment by sheerun** [comment]
thanks :)

**Comment by axelson** [comment]
Cool, thanks for the update!
